### ISSUE TITLE
Add swerve development documentation

### ISSUE THREAD

**Issue by redPlover** [team401/Docs#12]
**Summary**
Every year, we have to build new swerve boilerplate code. This is extremely time-consuming so we will create a step-by-step tutorial to use as a point of reference. This way we don't solve the same problems manually.

**Work Scope**

- [ ] Create steps to configure swerve boilerplate code for a new robot
- [ ] Use the 2024 Phoenix swerve framework
- [ ] Describe the benefits of doing it this way
- [ ] Implement AdvantageKit for data logging

**Comment by jkleiber** [comment]
This is pretty much done - as we gain more institutional knowledge, we can add to the existing page
