### ISSUE TITLE
Add coding standards to documentation

### ISSUE THREAD

**Issue by jkleiber** [team401/Docs#6]
**Summary**
The scope of this issue is to 1. decide on coding standards and 2. put them on the Docs website

**Work Scope**
- Define coding standards
- Add coding standards to the Docs

**Comment by redPlover** [comment]
We should use Google's Java style guide

**Comment by redPlover** [comment]
We still need to add

- [ ] "Format on Save" instructions
- [ ] Installing formatters
- [ ] File naming

**Comment by jkleiber** [comment]
This is effectively overcome by events now that we use spotless. We probably just need to add instructions for file naming

**Comment by jkleiber** [comment]
A stub page exists. We can add links to spotless and instructions for file/folder naming at a later time
